from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse, Response
from sqlalchemy.orm import Session
from core.database import get_db
from models.orm import Job
import json
import os
import hashlib
import datetime
from fpdf import FPDF

router = APIRouter()

def clean_pdf_text(text: str) -> str:
    """Sanitize unicode to latin-1 safe ASCII for FPDF 1.7.2."""
    if not text:
        return ""
    text = str(text)
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2022": "*",
        "⚠️": "[!]", "❌": "[X]", "✅": "[OK]", "🔍": "[SEARCH]", "🏛️": "[GOV]",
        "📰": "[NEWS]", "🔗": "[LINK]", "📅": "[DATE]", "🧠": "[AI]", "🕐": "[TIME]",
        "•": "*", "—": "--", "–": "-", "₹": "INR ", "🚨": "[ALERT]", "🎬": "[MEDIA]",
        "📊": "[METRICS]", "🔬": "[MODEL]", "🔒": "[SECURE]", "✓": "[OK]"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


class DeceptrixReportPDF(FPDF):
    def __init__(self, job_id: str, modality: str):
        super().__init__(orientation='P', unit='mm', format='A4')
        self.job_id = job_id
        self.modality = modality
        self.set_margins(12, 12, 12)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Header banner (dark premium background)
        self.set_fill_color(24, 25, 26)
        self.rect(0, 0, 210, 20, style='F')
        
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 90, 36)  # Accent orange
        self.set_xy(12, 5)
        self.cell(100, 5, "DECEPTRIX FORENSIC AUDIT REPORT", 0, 0, 'L')
        
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(200, 200, 200)
        self.set_xy(110, 5)
        self.cell(88, 5, f"CASE: {self.job_id[:20]}...", 0, 0, 'R')
        
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.set_xy(12, 11)
        self.cell(186, 4, "Smart India Hackathon 2026 | Explainable Media & Rumour Forensics | Court-Admissible Forensic Spec", 0, 0, 'L')
        
        self.set_text_color(30, 30, 30)
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.set_draw_color(200, 200, 200)
        self.line(12, 285, 198, 285)
        self.cell(110, 8, "DECEPTRIX v2.0 -- Cryptographically Hashed Forensic Audit Record", 0, 0, 'L')
        self.cell(76, 8, f"Page {self.page_no()}", 0, 0, 'R')


@router.get("/{job_id}.json")
def get_report_json(job_id: str, db: Session = Depends(get_db)):
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    report_payload = {
        "report_version": "2.0.0",
        "pipeline_version": "2.0.0-multi-modal",
        "id": job.id,
        "modality": job.modality,
        "status": job.status,
        "filename": job.filename,
        "sha256": job.sha256,
        "verdict": job.verdict,
        "progress": job.progress,
        "evidence": job.evidence or [],
        "report_data": job.report_data or {},
        "created_at": job.created_at.isoformat() if job.created_at else None,
        "completed_at": job.completed_at.isoformat() if job.completed_at else None,
        "disclaimer": (
            "This automated forensic report was generated by DECEPTRIX. "
            "Findings represent algorithmic assessments based on specified model versions and retrieved sources. "
            "It does not constitute a definitive legal certification."
        )
    }

    # Generate tamper-evident signature of this JSON record
    content_str = json.dumps(report_payload, sort_keys=True)
    report_payload["audit_record_hash"] = hashlib.sha256(content_str.encode('utf-8')).hexdigest()

    return JSONResponse(content=report_payload)


@router.get("/{job_id}.pdf")
def get_report_pdf(job_id: str, db: Session = Depends(get_db)):
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    pdf = DeceptrixReportPDF(job.id, job.modality)
    pdf.add_page()

    # ══════════════════════════════════════════════════════════════
    # 1. CHAIN OF CUSTODY & INGESTION PROVENANCE
    # ══════════════════════════════════════════════════════════════
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(186, 6, "1. Chain of Custody & Ingestion Provenance", 0, 1, 'L')

    pdf.set_fill_color(248, 249, 251)
    pdf.set_draw_color(215, 220, 226)
    pdf.rect(12, pdf.get_y(), 186, 28, style='FD')

    cur_y = pdf.get_y() + 2
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(50, 50, 50)
    
    # Row 1
    pdf.set_xy(15, cur_y)
    pdf.cell(32, 4.5, "Case Audit ID:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(62, 4.5, clean_pdf_text(job.id[:28] + "..."), 0, 0)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "Modality / Type:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(56, 4.5, f"{job.modality.upper()} FORENSIC AUDIT", 0, 1)

    # Row 2
    pdf.set_xy(15, cur_y + 5)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "Input Filename:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(62, 4.5, clean_pdf_text((job.filename or "Raw text input")[:30]), 0, 0)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "Submitted Time:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(56, 4.5, job.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if job.created_at else 'N/A', 0, 1)

    # Row 3
    pdf.set_xy(15, cur_y + 10)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "Execution Cluster:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(62, 4.5, "DECEPTRIX Node DX-01", 0, 0)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "Completed Time:", 0, 0)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(56, 4.5, job.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if job.completed_at else 'N/A', 0, 1)

    # Row 4: SHA-256
    pdf.set_xy(15, cur_y + 15.5)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(32, 4.5, "SHA-256 Digest:", 0, 0)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(255, 90, 36)
    pdf.cell(150, 4.5, clean_pdf_text(job.sha256 or 'N/A'), 0, 1)

    pdf.set_y(cur_y + 28)

    # ══════════════════════════════════════════════════════════════
    # 2. EXECUTIVE VERDICT & THREAT CLASSIFICATION
    # ══════════════════════════════════════════════════════════════
    pdf.ln(3)
    verdict = job.verdict or "Inconclusive"
    
    # Calculate composite score from evidence if not saved
    all_face_items = []
    df_scores = []
    jitter_scores = []
    freq_scores = []
    lip_sync_score = 0.0
    meta_score = 0.15

    if job.evidence:
        for ev in job.evidence:
            if ev.get("modality") == "metadata" and ev.get("score_or_null") is not None:
                meta_score = float(ev["score_or_null"])
            elif ev.get("modality") == "audio_visual" and ev.get("score_or_null") is not None:
                lip_sync_score = float(ev["score_or_null"])
            
            refs = ev.get("artifact_refs") or []
            for ref in refs:
                ts = ref.get("timestamp_sec", 0)
                faces = ref.get("faces") or []
                for face in faces:
                    fs = float(face.get("fake_score", 0.0))
                    js = float(face.get("jitter_score", 0.0))
                    fr = float(face.get("freq_score", 0.0))
                    df_scores.append(fs)
                    jitter_scores.append(js)
                    freq_scores.append(fr)
                    all_face_items.append({
                        "timestamp_sec": ts,
                        "fake_score": fs,
                        "jitter_score": js,
                        "freq_score": fr,
                        "face_crop": face.get("face_crop", ""),
                        "bbox": face.get("bbox", [])
                    })

    max_df = max(df_scores) if df_scores else 0.0
    max_jit = max(jitter_scores) if jitter_scores else 0.0
    max_freq = max(freq_scores) if freq_scores else 0.0
    
    calc_final_score = (max_df * 0.35) + (lip_sync_score * 0.25) + (max_jit * 0.15) + (max_freq * 0.15) + (meta_score * 0.10)
    final_score = (job.report_data or {}).get("final_score") or calc_final_score

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(186, 6, "2. Executive Verdict & Threat Classification", 0, 1, 'L')

    if "Manipulated" in verdict or "Contradicted" in verdict or final_score > 0.4:
        pdf.set_fill_color(255, 238, 238)
        pdf.set_draw_color(220, 50, 50)
        verdict_color = (190, 20, 20)
        risk_level = "CRITICAL RISK (SYNTHETIC MEDIA DETECTED)"
        verdict = "Likely Manipulated"
    elif "Real" in verdict or "Supported" in verdict:
        pdf.set_fill_color(238, 252, 242)
        pdf.set_draw_color(40, 170, 90)
        verdict_color = (20, 130, 50)
        risk_level = "LOW RISK (NATURAL BIOMETRICS & METADATA)"
    else:
        pdf.set_fill_color(255, 250, 235)
        pdf.set_draw_color(220, 160, 30)
        verdict_color = (180, 120, 10)
        risk_level = "ELEVATED RISK (SUSPICIOUS ARTIFACTS DETECTED)"

    banner_y = pdf.get_y()
    pdf.rect(12, banner_y, 186, 20, style='FD')

    pdf.set_xy(16, banner_y + 2.5)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*verdict_color)
    pdf.cell(100, 6, f"VERDICT: {clean_pdf_text(verdict).upper()}", 0, 0)

    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(76, 6, f"Composite Anomaly: {final_score:.2f} / 1.00", 0, 1, 'R')

    pdf.set_xy(16, banner_y + 9)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*verdict_color)
    pdf.cell(100, 4, risk_level, 0, 0)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(76, 4, "Evaluated against 5-Signal Bayesian Ensemble", 0, 1, 'R')

    pdf.set_xy(16, banner_y + 13.5)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(70, 70, 70)
    if "Manipulated" in verdict:
        desc_text = "Analysis detected high-confidence synthetic facial synthesis artifacts and acoustic-visual desynchronization."
    elif "Real" in verdict:
        desc_text = "Analysis found no high-confidence synthetic manipulation artifacts within sampled keyframes and container streams."
    else:
        desc_text = "Analysis identified anomalies; manual forensic inspection recommended before final determination."
    pdf.cell(176, 4, clean_pdf_text(desc_text), 0, 1)

    pdf.set_y(banner_y + 23)

    # ══════════════════════════════════════════════════════════════
    # 3. 5-SIGNAL BAYESIAN MULTI-MODAL ENSEMBLE TABLE
    # ══════════════════════════════════════════════════════════════
    if job.modality == "media":
        saved_signals = (job.report_data or {}).get("signal_scores", {})
        
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(186, 6, "3. 5-Signal Bayesian Multi-Modal Ensemble Matrix", 0, 1, 'L')

        # Table Header
        pdf.set_fill_color(240, 242, 245)
        pdf.set_draw_color(210, 215, 220)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(40, 40, 40)
        
        pdf.cell(50, 6, "Signal Modality", 1, 0, 'L', fill=True)
        pdf.cell(48, 6, "Underlying AI Model / Method", 1, 0, 'L', fill=True)
        pdf.cell(20, 6, "Weight", 1, 0, 'C', fill=True)
        pdf.cell(24, 6, "Score (0-1)", 1, 0, 'C', fill=True)
        pdf.cell(44, 6, "Threshold & Risk Status", 1, 1, 'C', fill=True)

        vit_sc = saved_signals.get("deepfake_classifier", max_df)
        lip_sc = saved_signals.get("lip_sync", lip_sync_score)
        jit_sc = saved_signals.get("jitter", max_jit)
        dct_sc = saved_signals.get("frequency", max_freq)
        met_sc = saved_signals.get("metadata", meta_score)

        signals_meta = [
            ("ViT Deepfake Texture", "dima806/ViT-Patch16", "35%", vit_sc, 0.5),
            ("Lip-Sync Correlation", "MediaPipe MAR + Librosa RMS", "25%", lip_sc, 0.5),
            ("Landmark Jitter Variance", "MediaPipe 468-pt Mesh", "15%", jit_sc, 0.4),
            ("2D-DCT Spectral Frequency", "Scipy FFT Sub-Pixel Norm", "15%", dct_sc, 0.4),
            ("Container & Codec Metadata", "FFprobe Stream Header Parser", "10%", met_sc, 0.2),
        ]

        pdf.set_font("Helvetica", "", 8)
        for name, method, wt, score, thresh in signals_meta:
            pdf.cell(50, 5, name, 1, 0, 'L')
            pdf.cell(48, 5, method, 1, 0, 'L')
            pdf.cell(20, 5, wt, 1, 0, 'C')
            
            # Score cell
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(24, 5, f"{score:.2f} / 1.00", 1, 0, 'C')
            
            # Status cell
            if score > thresh + 0.2:
                pdf.set_text_color(190, 20, 20)
                status_txt = "[!] HIGH RISK (Exceeded)"
            elif score > thresh:
                pdf.set_text_color(180, 120, 10)
                status_txt = "[?] ELEVATED (Borderline)"
            else:
                pdf.set_text_color(20, 130, 50)
                status_txt = "[OK] NORMAL (Clean)"
            
            pdf.cell(44, 5, status_txt, 1, 1, 'C')
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(50, 50, 50)

        pdf.ln(3)

        # ══════════════════════════════════════════════════════════════
        # 4. TECHNICAL CONTAINER & STREAM METADATA TABLE
        # ══════════════════════════════════════════════════════════════
        metadata = (job.report_data or {}).get("metadata", {})
        if metadata:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(186, 6, "4. Technical Container & Stream Telemetry", 0, 1, 'L')

            pdf.set_fill_color(248, 249, 251)
            pdf.set_draw_color(210, 215, 220)
            
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(46, 5, "Property", 1, 0, 'L', fill=True)
            pdf.cell(47, 5, "Detected Value", 1, 0, 'L', fill=True)
            pdf.cell(46, 5, "Property", 1, 0, 'L', fill=True)
            pdf.cell(47, 5, "Detected Value", 1, 1, 'L', fill=True)

            pdf.set_font("Helvetica", "", 8)
            pdf.cell(46, 4.5, "Duration / Sampling", 1, 0, 'L')
            pdf.cell(47, 4.5, f"{metadata.get('duration', 0):.1f}s (15 FPS dense)", 1, 0, 'L')
            pdf.cell(46, 4.5, "Resolution & Aspect", 1, 0, 'L')
            pdf.cell(47, 4.5, f"{metadata.get('width', 0)} x {metadata.get('height', 0)} px", 1, 1, 'L')

            pdf.cell(46, 4.5, "Video Codec / Stream", 1, 0, 'L')
            pdf.cell(47, 4.5, f"{metadata.get('video_codec', 'h264').upper()} ({metadata.get('fps', 24):.1f} FPS)", 1, 0, 'L')
            pdf.cell(46, 4.5, "Audio Stream / Sample", 1, 0, 'L')
            pdf.cell(47, 4.5, f"{metadata.get('audio_codec', 'aac').upper()} @ {metadata.get('audio_sample_rate', 48000)} Hz", 1, 1, 'L')

            pdf.cell(46, 4.5, "Container Format", 1, 0, 'L')
            pdf.cell(47, 4.5, clean_pdf_text(str(metadata.get('format_name', 'mp4'))[:24]), 1, 0, 'L')
            pdf.cell(46, 4.5, "Creation Header Tag", 1, 0, 'L')
            pdf.cell(47, 4.5, "Present" if metadata.get('has_creation_date') else "Missing / Stripped", 1, 1, 'L')

            pdf.ln(3)

        # ══════════════════════════════════════════════════════════════
        # 5. PIPELINE ARCHITECTURE FLOW DIAGRAM (ASCII BOX SPEC)
        # ══════════════════════════════════════════════════════════════
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(186, 6, "5. DECEPTRIX Multi-Modal Architectural Flow", 0, 1, 'L')

        flow_y = pdf.get_y()
        pdf.set_fill_color(245, 247, 250)
        pdf.set_draw_color(200, 205, 212)
        pdf.rect(12, flow_y, 186, 12, style='FD')

        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(60, 60, 60)
        pdf.set_xy(14, flow_y + 2)
        pdf.cell(182, 4, "[INSPECTION INTAKE]  ==>  [DENSE 15 FPS SAMPLING]  ==>  [5 PARALLEL FORENSIC ENGINES]  ==>  [BAYESIAN FUSION]", 0, 1, 'C')
        pdf.set_xy(14, flow_y + 6.5)
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(182, 4, "SHA-256 Fingerprint       FFmpeg / Librosa 16kHz      ViT / MAR / Mesh / DCT / FFprobe        Cryptographic PDF/JSON Attestation", 0, 1, 'C')

        pdf.set_y(flow_y + 15)

        # ══════════════════════════════════════════════════════════════
        # 6. FRAME-BY-FRAME KEYFRAME FACIAL EXTRACTION GALLERY
        # ══════════════════════════════════════════════════════════════
        all_face_items = []
        if job.evidence:
            for ev in job.evidence:
                refs = ev.get("artifact_refs") or []
                for ref in refs:
                    ts = ref.get("timestamp_sec", 0)
                    faces = ref.get("faces") or []
                    for face in faces:
                        all_face_items.append({
                            "timestamp_sec": ts,
                            "fake_score": face.get("fake_score", 0.0),
                            "jitter_score": face.get("jitter_score", 0.0),
                            "freq_score": face.get("freq_score", 0.0),
                            "face_crop": face.get("face_crop", ""),
                            "bbox": face.get("bbox", [])
                        })

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(186, 6, "6. Keyframe Facial Extraction & Biometric Forensics Gallery", 0, 1, 'L')

        if all_face_items:
            for idx, item in enumerate(all_face_items):
                # Check for page break (each card is 26mm tall)
                if pdf.get_y() > 240:
                    pdf.add_page()

                ts = item["timestamp_sec"]
                mins = int(ts) // 60
                secs = int(ts) % 60
                time_str = f"{mins:02d}:{secs:02d}s"

                card_y = pdf.get_y()
                fake_s = item["fake_score"]

                # Card background and border
                if fake_s > 0.6:
                    pdf.set_fill_color(255, 248, 248)
                    pdf.set_draw_color(230, 160, 160)
                elif fake_s > 0.4:
                    pdf.set_fill_color(255, 252, 245)
                    pdf.set_draw_color(230, 200, 140)
                else:
                    pdf.set_fill_color(248, 252, 249)
                    pdf.set_draw_color(170, 220, 190)

                pdf.rect(12, card_y, 186, 25, style='FD')

                # Embed real cropped face image
                crop_path = item["face_crop"]
                has_image = False
                if crop_path and os.path.exists(crop_path):
                    try:
                        # Draw image with 2mm inner margin
                        pdf.image(crop_path, x=14, y=card_y + 2, w=21, h=21)
                        has_image = True
                    except Exception:
                        has_image = False

                text_start_x = 38 if has_image else 16

                # Title & Timestamp Header
                pdf.set_xy(text_start_x, card_y + 2)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(30, 30, 30)
                bbox_str = f"BBox: {item.get('bbox', [])}" if item.get('bbox') else ""
                pdf.cell(85, 4, f"Keyframe #{idx + 1:02d} (Time: {time_str})  {bbox_str}", 0, 0)

                # Status Badge
                pdf.set_font("Helvetica", "B", 8)
                if fake_s > 0.6:
                    pdf.set_text_color(190, 20, 20)
                    pdf.cell(70, 4, "[!] HIGH MANIPULATION RISK", 0, 1, 'R')
                elif fake_s > 0.4:
                    pdf.set_text_color(180, 120, 10)
                    pdf.cell(70, 4, "[?] SUSPICIOUS ARTIFACTS", 0, 1, 'R')
                else:
                    pdf.set_text_color(20, 130, 50)
                    pdf.cell(70, 4, "[OK] NATURAL TEXTURE", 0, 1, 'R')

                # Forensic Measurements Grid
                pdf.set_xy(text_start_x, card_y + 7)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(50, 4, f"ViT Probability: {item['fake_score'] * 100:.1f}% Synthetic", 0, 0)
                pdf.cell(50, 4, f"DCT Frequency Anomaly: {item['freq_score']:.2f}", 0, 0)
                pdf.cell(55, 4, f"Landmark Jitter: {item['jitter_score']:.2f}", 0, 1)

                # Diagnostic Summary
                pdf.set_xy(text_start_x, card_y + 12)
                pdf.set_font("Helvetica", "I", 7.5)
                pdf.set_text_color(90, 90, 90)
                if fake_s > 0.6:
                    diag = "Vision Transformer flagged high-confidence generative neural synthesis patterns in facial boundary and skin texture."
                elif fake_s > 0.4:
                    diag = "Moderate spatial or frequency irregularity detected; boundary blending requires attention."
                else:
                    diag = "Facial boundary coherence and landmark stability remain consistent with authentic camera recording."
                
                pdf.multi_cell(156, 3.5, clean_pdf_text(diag))

                pdf.set_y(card_y + 27)
        else:
            pdf.set_font("Helvetica", "I", 8.5)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(186, 5, "No prominent human faces detected in sampled video keyframes.", 0, 1)
            pdf.ln(3)

    elif job.modality == "text":
        # ── Claims & Fact-Checking Outcomes Table ──
        claims = (job.report_data or {}).get("extracted_claims", [])
        if claims:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(186, 6, "3. Extracted Atomic Claims & Fact-Checking Table", 0, 1, 'L')

            for idx, c in enumerate(claims):
                if pdf.get_y() > 240:
                    pdf.add_page()

                outcome = c.get("outcome", "Unsupported")
                card_y = pdf.get_y()
                pdf.set_fill_color(250, 251, 253)
                pdf.set_draw_color(220, 225, 230)
                pdf.rect(12, card_y, 186, 26, style='FD')

                pdf.set_xy(15, card_y + 2)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(120, 4, f"Claim #{idx + 1}:", 0, 0)

                # Outcome badge
                pdf.set_font("Helvetica", "B", 8)
                if outcome == "Contradicted":
                    pdf.set_text_color(190, 20, 20)
                    pdf.cell(56, 4, "[!] CONTRADICTED (FALSE)", 0, 1, 'R')
                elif outcome == "Supported":
                    pdf.set_text_color(20, 130, 50)
                    pdf.cell(56, 4, "[OK] SUPPORTED (TRUE)", 0, 1, 'R')
                else:
                    pdf.set_text_color(180, 120, 10)
                    pdf.cell(56, 4, "[?] UNSUPPORTED / UNVERIFIED", 0, 1, 'R')

                # Claim Text
                pdf.set_xy(15, card_y + 7)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(180, 3.8, clean_pdf_text(c.get("text", "")))

                # Source citation
                citations = c.get("citations", [])
                if citations:
                    pdf.set_xy(15, card_y + 16)
                    pdf.set_font("Helvetica", "I", 7.5)
                    pdf.set_text_color(100, 100, 100)
                    cit = citations[0]
                    pdf.cell(180, 4, f"Primary Source (Tier {cit.get('tier', 3)}): {clean_pdf_text(cit.get('title') or cit.get('url'))[:80]}...", 0, 1)

                pdf.set_y(card_y + 29)

    # ══════════════════════════════════════════════════════════════
    # 7. DIAGNOSTIC EVIDENCE TIMELINE & EVENT LOG
    # ══════════════════════════════════════════════════════════════
    if pdf.get_y() > 235:
        pdf.add_page()

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    sec_num_ev = "7" if job.modality == "media" else "4"
    pdf.cell(186, 6, f"{sec_num_ev}. Complete Forensic Evidence Timeline", 0, 1, 'L')

    if job.evidence:
        pdf.set_font("Helvetica", "", 8)
        for ev in job.evidence:
            if pdf.get_y() > 255:
                pdf.add_page()

            typ = ev.get("type", "Unknown")
            score = ev.get("score_or_null")
            expl = clean_pdf_text(ev.get("explanation", ""))
            model = clean_pdf_text(ev.get("model_or_connector", "N/A"))

            score_str = f"(Anomaly Score: {score:.2f})" if score is not None else ""
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(186, 4.5, f"* {typ.replace('_', ' ').title()} {score_str} -- Model: {model}", 0, 1)

            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(186, 3.8, f"  {expl}")
            pdf.ln(1)
    else:
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(186, 4.5, "No technical anomalies or evidence events recorded.", 0, 1)

    pdf.ln(3)

    # ══════════════════════════════════════════════════════════════
    # 8. CRYPTOGRAPHIC VERIFICATION & LEGAL DISCLAIMER
    # ══════════════════════════════════════════════════════════════
    if pdf.get_y() > 240:
        pdf.add_page()

    pdf.set_fill_color(246, 247, 249)
    pdf.set_draw_color(210, 215, 220)
    pdf.rect(12, pdf.get_y(), 186, 26, style='FD')

    cur_y = pdf.get_y() + 1.5
    pdf.set_xy(15, cur_y)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(50, 50, 50)
    sec_num_disc = "8" if job.modality == "media" else "5"
    pdf.cell(180, 4, f"{sec_num_disc}. Cryptographic Verification & Legal Disclaimer", 0, 1)

    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(90, 90, 90)
    disclaimers = [
        "- This audit document is an algorithmic forensic assessment produced by DECEPTRIX multi-signal pipeline.",
        "- Video analysis operates on sampled keyframes (15 FPS); unseen non-sampled frames are not evaluated.",
        "- Platform compression, transcoding, or noise can alter high-frequency DCT / landmark jitter measurements.",
        "- Full tamper-evident JSON payload hash: SHA-256(Record) = " + str(job.sha256 or 'N/A')[:40] + "..."
    ]
    for d in disclaimers:
        pdf.set_x(15)
        pdf.cell(180, 3.6, clean_pdf_text(d), 0, 1)

    pdf_bytes = pdf.output(dest='S').encode('latin1')
    return Response(content=pdf_bytes, media_type="application/pdf")
