from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse, Response
from sqlalchemy.orm import Session
from core.database import get_db
from models.orm import Job
import json
import os
import hashlib
import datetime
from fpdf import FPDF

router = APIRouter()

def clean_pdf_text(text: str) -> str:
    """Sanitize unicode to latin-1 safe ASCII for FPDF 1.7.2."""
    if not text:
        return ""
    text = str(text)
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2022": "*",
        "⚠️": "[!]", "❌": "[X]", "✅": "[OK]", "🔍": "[SEARCH]", "🏛️": "[GOV]",
        "📰": "[NEWS]", "🔗": "[LINK]", "📅": "[DATE]", "🧠": "[AI]", "🕐": "[TIME]",
        "•": "*", "—": "--", "–": "-", "₹": "INR "
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


class DeceptrixReportPDF(FPDF):
    def __init__(self, job_id: str, modality: str):
        super().__init__(orientation='P', unit='mm', format='A4')
        self.job_id = job_id
        self.modality = modality
        self.set_margins(12, 12, 12)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Header banner
        self.set_fill_color(24, 25, 26)  # Dark background
        self.rect(0, 0, 210, 20, style='F')
        
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 90, 36)  # Accent orange
        self.set_xy(12, 5)
        self.cell(100, 5, "DECEPTRIX FORENSIC AUDIT REPORT", 0, 0, 'L')
        
        self.set_font("Helvetica", "", 9)
        self.set_text_color(180, 180, 180)
        self.set_xy(110, 5)
        self.cell(88, 5, f"Case: {self.job_id[:16]}...", 0, 0, 'R')
        
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.set_xy(12, 11)
        self.cell(186, 4, "Smart India Hackathon 2026 | Explainable Media & Rumour Forensics | Evidence Before Conclusions", 0, 0, 'L')
        
        self.set_text_color(30, 30, 30)
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.set_draw_color(200, 200, 200)
        self.line(12, 285, 198, 285)
        self.cell(100, 8, "DECEPTRIX v2.0-MVP -- Cryptographically Hashed Forensic Output", 0, 0, 'L')
        self.cell(86, 8, f"Page {self.page_no()}", 0, 0, 'R')


@router.get("/{job_id}.json")
def get_report_json(job_id: str, db: Session = Depends(get_db)):
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    report_payload = {
        "report_version": "2.0.0",
        "pipeline_version": "2.0.0-multi-modal",
        "id": job.id,
        "modality": job.modality,
        "status": job.status,
        "filename": job.filename,
        "sha256": job.sha256,
        "verdict": job.verdict,
        "progress": job.progress,
        "evidence": job.evidence or [],
        "report_data": job.report_data or {},
        "created_at": job.created_at.isoformat() if job.created_at else None,
        "completed_at": job.completed_at.isoformat() if job.completed_at else None,
        "disclaimer": (
            "This automated forensic report was generated by DECEPTRIX. "
            "Findings represent algorithmic assessments based on specified model versions and retrieved sources. "
            "It does not constitute a definitive legal certification."
        )
    }

    # Generate tamper-evident signature of this JSON record
    content_str = json.dumps(report_payload, sort_keys=True)
    report_payload["audit_record_hash"] = hashlib.sha256(content_str.encode('utf-8')).hexdigest()

    return JSONResponse(content=report_payload)


@router.get("/{job_id}.pdf")
def get_report_pdf(job_id: str, db: Session = Depends(get_db)):
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    pdf = DeceptrixReportPDF(job.id, job.modality)
    pdf.add_page()

    # ── Section 1: Case Summary Box ──
    pdf.set_fill_color(245, 246, 248)
    pdf.set_draw_color(210, 215, 220)
    pdf.rect(12, 22, 186, 32, style='FD')

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.set_xy(15, 24)
    pdf.cell(90, 5, f"Case ID: {job.id}", 0, 0)
    pdf.cell(90, 5, f"Modality: {job.modality.upper()} AUDIT", 0, 1)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.set_x(15)
    pdf.cell(90, 5, f"Filename: {clean_pdf_text(job.filename or 'Raw text payload')}", 0, 0)
    pdf.cell(90, 5, f"Submitted: {job.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if job.created_at else 'N/A'}", 0, 1)

    pdf.set_x(15)
    pdf.cell(90, 5, f"SHA-256: {(job.sha256[:20] + '...') if job.sha256 else 'N/A'}", 0, 0)
    pdf.cell(90, 5, f"Completed: {job.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if job.completed_at else 'N/A'}", 0, 1)

    pdf.set_x(15)
    pdf.cell(90, 5, f"Full SHA-256: {clean_pdf_text(job.sha256 or 'N/A')}", 0, 1)

    pdf.ln(5)

    # ── Section 2: Technical Media Metadata (if available) ──
    metadata = {}
    if job.report_data and "metadata" in job.report_data:
        metadata = job.report_data.get("metadata", {})

    if metadata:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(186, 6, "1. Technical Media Container & Stream Metadata", 0, 1, 'L')

        pdf.set_fill_color(250, 250, 252)
        pdf.rect(12, pdf.get_y(), 186, 16, style='FD')
        
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(70, 70, 70)
        cur_y = pdf.get_y() + 1
        pdf.set_xy(15, cur_y)
        pdf.cell(45, 4, f"Duration: {metadata.get('duration', 0):.1f}s", 0, 0)
        pdf.cell(45, 4, f"Resolution: {metadata.get('width', 0)}x{metadata.get('height', 0)}", 0, 0)
        pdf.cell(45, 4, f"Video Codec: {metadata.get('video_codec', 'none')}", 0, 0)
        pdf.cell(45, 4, f"FPS: {metadata.get('fps', 0):.1f}", 0, 1)

        pdf.set_xy(15, cur_y + 5)
        pdf.cell(45, 4, f"Container: {clean_pdf_text(metadata.get('format_name', 'unknown'))}", 0, 0)
        pdf.cell(45, 4, f"Audio Codec: {metadata.get('audio_codec', 'none')}", 0, 0)
        pdf.cell(45, 4, f"Sample Rate: {metadata.get('audio_sample_rate', 0)} Hz", 0, 0)
        pdf.cell(45, 4, f"Creation Tag: {'Present' if metadata.get('has_creation_date') else 'Missing'}", 0, 1)

        pdf.set_xy(15, cur_y + 10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(180, 4, "Metadata extracted via FFprobe container stream parser.", 0, 1)
        pdf.ln(5)

    # ── Section 3: Verdict Banner ──
    verdict = job.verdict or "Inconclusive"
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(186, 6, "2. Executive Verdict & Confidence", 0, 1, 'L')

    if "Manipulated" in verdict or "Contradicted" in verdict:
        pdf.set_fill_color(255, 235, 235)
        pdf.set_draw_color(230, 70, 70)
        pdf.rect(12, pdf.get_y(), 186, 18, style='FD')
        pdf.set_text_color(190, 20, 20)
    elif "Real" in verdict or "Supported" in verdict:
        pdf.set_fill_color(235, 250, 240)
        pdf.set_draw_color(40, 170, 90)
        pdf.rect(12, pdf.get_y(), 186, 18, style='FD')
        pdf.set_text_color(20, 130, 50)
    else:
        pdf.set_fill_color(255, 248, 230)
        pdf.set_draw_color(220, 160, 30)
        pdf.rect(12, pdf.get_y(), 186, 18, style='FD')
        pdf.set_text_color(180, 120, 10)

    cur_y = pdf.get_y() + 2
    pdf.set_xy(15, cur_y)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(120, 6, f"VERDICT: {clean_pdf_text(verdict).upper()}", 0, 0)
    
    final_score = (job.report_data or {}).get("final_score")
    if final_score is not None:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(60, 6, f"Composite Anomaly Score: {final_score:.2f} / 1.00", 0, 1, 'R')
    else:
        pdf.ln(6)

    pdf.set_xy(15, cur_y + 7)
    pdf.set_font("Helvetica", "", 9)
    if "Manipulated" in verdict:
        pdf.cell(180, 5, "Forensic signals exceed threshold for synthetic/manipulated media artifacts.", 0, 1)
    elif "Contradicted" in verdict:
        pdf.cell(180, 5, "Retrieved authoritative sources contradict one or more extracted claims.", 0, 1)
    elif "Supported" in verdict:
        pdf.cell(180, 5, "Public evidence and authoritative reporting support the verified claims.", 0, 1)
    elif "Real" in verdict:
        pdf.cell(180, 5, "No significant technical anomalies detected within analyzed frame coverage.", 0, 1)
    else:
        pdf.cell(180, 5, "Analysis is inconclusive or evidence is insufficient for definitive categorization.", 0, 1)

    pdf.ln(8)

    # ── Section 4: Multi-Modal Signal Breakdown (Media) or Claims (Text) ──
    if job.modality == "media":
        signal_scores = (job.report_data or {}).get("signal_scores", {})

        if signal_scores:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(186, 6, "3. Multi-Modal Ensemble Signal Breakdown", 0, 1, 'L')

            pdf.set_fill_color(248, 249, 250)
            pdf.set_draw_color(220, 225, 230)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(60, 60, 60)

            # Table header
            pdf.cell(60, 6, "Signal Modality", 1, 0, 'L', fill=True)
            pdf.cell(45, 6, "Model / Method", 1, 0, 'L', fill=True)
            pdf.cell(25, 6, "Weight", 1, 0, 'C', fill=True)
            pdf.cell(25, 6, "Score (0-1)", 1, 0, 'C', fill=True)
            pdf.cell(31, 6, "Status", 1, 1, 'C', fill=True)

            signals_meta = [
                ("ViT Deepfake Classifier", "dima806/ViT-Patch16", "35%", signal_scores.get("deepfake_classifier", 0.0)),
                ("Lip-Sync Correlation", "MediaPipe MAR + Librosa RMS", "25%", signal_scores.get("lip_sync", 0.0)),
                ("Facial Landmark Jitter", "MediaPipe Mesh Variance", "15%", signal_scores.get("jitter", 0.0)),
                ("DCT Frequency Analysis", "Scipy Spectral Norm", "15%", signal_scores.get("frequency", 0.0)),
                ("Technical Metadata", "FFprobe Container Check", "10%", signal_scores.get("metadata", 0.0)),
            ]

            pdf.set_font("Helvetica", "", 8.5)
            for name, method, wt, score in signals_meta:
                pdf.cell(60, 5, name, 1, 0, 'L')
                pdf.cell(45, 5, method, 1, 0, 'L')
                pdf.cell(25, 5, wt, 1, 0, 'C')
                pdf.cell(25, 5, f"{score:.2f}", 1, 0, 'C')
                status_txt = "Anomalous" if score > 0.5 else "Normal"
                pdf.cell(31, 5, status_txt, 1, 1, 'C')

            pdf.ln(5)

        # ── Dedicated Section 4: Keyframe Face Extraction & Forensics Gallery ──
        all_face_items = []
        if job.evidence:
            for ev in job.evidence:
                refs = ev.get("artifact_refs") or []
                for ref in refs:
                    ts = ref.get("timestamp_sec", 0)
                    faces = ref.get("faces") or []
                    for face in faces:
                        all_face_items.append({
                            "timestamp_sec": ts,
                            "fake_score": face.get("fake_score", 0.0),
                            "jitter_score": face.get("jitter_score", 0.0),
                            "freq_score": face.get("freq_score", 0.0),
                            "face_crop": face.get("face_crop", "")
                        })

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(186, 6, "4. Keyframe Facial Extraction & Frame-by-Frame Forensics Gallery", 0, 1, 'L')

        if all_face_items:
            for idx, item in enumerate(all_face_items):
                # Page break check
                if pdf.get_y() > 230:
                    pdf.add_page()

                ts = item["timestamp_sec"]
                mins = int(ts) // 60
                secs = int(ts) % 60
                time_str = f"{mins:02d}:{secs:02d}s"

                card_y = pdf.get_y()
                pdf.set_fill_color(252, 252, 254)
                pdf.set_draw_color(220, 225, 230)
                pdf.rect(12, card_y, 186, 26, style='FD')

                # Embed face image if it exists
                crop_path = item["face_crop"]
                has_image = False
                if crop_path and os.path.exists(crop_path):
                    try:
                        pdf.image(crop_path, x=15, y=card_y + 2, w=22, h=22)
                        has_image = True
                    except Exception:
                        has_image = False

                text_start_x = 42 if has_image else 16
                pdf.set_xy(text_start_x, card_y + 3)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(90, 4, f"Face Detection #{idx + 1} -- Keyframe at {time_str}", 0, 0)

                # Local badge
                fake_s = item["fake_score"]
                pdf.set_font("Helvetica", "B", 8)
                if fake_s > 0.6:
                    pdf.set_text_color(190, 20, 20)
                    pdf.cell(60, 4, "[!] HIGH MANIPULATION RISK", 0, 1, 'R')
                elif fake_s > 0.4:
                    pdf.set_text_color(180, 120, 10)
                    pdf.cell(60, 4, "[?] SUSPICIOUS ARTIFACTS", 0, 1, 'R')
                else:
                    pdf.set_text_color(20, 130, 50)
                    pdf.cell(60, 4, "[OK] NATURAL TEXTURE", 0, 1, 'R')

                # Scores line
                pdf.set_xy(text_start_x, card_y + 8)
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(80, 80, 80)
                pdf.cell(150, 4, f"ViT Deepfake Score: {item['fake_score']:.2f}  |  DCT High-Freq Anomaly: {item['freq_score']:.2f}  |  Landmark Jitter: {item['jitter_score']:.2f}", 0, 1)

                # Diagnostics description
                pdf.set_xy(text_start_x, card_y + 13)
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(110, 110, 110)
                if fake_s > 0.6:
                    diag = "Vision Transformer flagged generative neural network face synthesis patterns in facial boundary/skin texture."
                elif fake_s > 0.4:
                    diag = "Mild generative artifacts or high-frequency anomalies detected; manual inspection recommended."
                else:
                    diag = "Facial landmarks and frequency distribution remain consistent with authentic recording."
                pdf.cell(150, 4, clean_pdf_text(diag), 0, 1)

                pdf.set_y(card_y + 28)
        else:
            pdf.set_font("Helvetica", "I", 8.5)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(186, 5, "No prominent human faces detected within sampled keyframes.", 0, 1)
            pdf.ln(3)

    elif job.modality == "text":
        claims = (job.report_data or {}).get("extracted_claims", [])
        if claims:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(186, 6, "3. Extracted Atomic Claims & Fact-Checking Outcomes", 0, 1, 'L')

            for idx, c in enumerate(claims):
                outcome = c.get("outcome", "Unsupported")
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(50, 50, 50)
                pdf.cell(186, 5, f"Claim #{idx + 1}: [{outcome.upper()}]", 0, 1)

                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(186, 4.5, clean_pdf_text(c.get("text", "")))

                citations = c.get("citations", [])
                if citations:
                    pdf.set_font("Helvetica", "I", 8)
                    for cit in citations[:2]:
                        pdf.cell(186, 4, f"   -> Source (Tier {cit.get('tier', 3)}): {clean_pdf_text(cit.get('title') or cit.get('url'))}", 0, 1)
                        if cit.get("snippet"):
                            pdf.set_text_color(110, 110, 110)
                            pdf.multi_cell(186, 3.5, f"      \"{clean_pdf_text(cit.get('snippet')[:140])}...\"")
                            pdf.set_text_color(80, 80, 80)

                pdf.ln(2)

            pdf.ln(3)

    # ── Section 5: Evidence Timeline & Artifacts ──
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 30, 30)
    sec_num = "5" if job.modality == "media" else "4"
    pdf.cell(186, 6, f"{sec_num}. Diagnostic Evidence Timeline", 0, 1, 'L')

    if job.evidence:
        pdf.set_font("Helvetica", "", 8.5)
        for ev in job.evidence:
            if pdf.get_y() > 255:
                pdf.add_page()

            typ = ev.get("type", "Unknown")
            score = ev.get("score_or_null")
            expl = clean_pdf_text(ev.get("explanation", ""))
            model = clean_pdf_text(ev.get("model_or_connector", "N/A"))

            score_str = f"(Score: {score:.2f})" if score is not None else ""
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(186, 5, f"* {typ.replace('_', ' ').title()} {score_str} -- Model: {model}", 0, 1)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(186, 4, f"  {expl}")
            pdf.ln(1)
    else:
        pdf.set_font("Helvetica", "I", 8.5)
        pdf.cell(186, 5, "No technical anomalies or evidence events recorded.", 0, 1)

    pdf.ln(4)

    # ── Section 6: Limitations & Legal Disclaimer ──
    if pdf.get_y() > 240:
        pdf.add_page()

    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(200, 200, 200)
    pdf.rect(12, pdf.get_y(), 186, 26, style='FD')

    cur_y = pdf.get_y() + 1.5
    pdf.set_xy(15, cur_y)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(60, 60, 60)
    sec_num_disc = "6" if job.modality == "media" else "5"
    pdf.cell(180, 4, f"{sec_num_disc}. Forensic Scope & Legal Disclaimer", 0, 1)

    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(90, 90, 90)
    disclaimers = [
        "- This report is an automated diagnostic assessment and does not constitute a court-admissible certificate of truth.",
        "- Video analysis operates on sampled keyframe sequences (15 FPS); non-sampled frames are not evaluated.",
        "- Social media re-compression, transcoding, or noise can produce false positive frequency/jitter artifacts.",
        "- Text fact-checking relies on search engine indexes at audit execution time and does not prove future events.",
    ]
    for d in disclaimers:
        pdf.set_x(15)
        pdf.cell(180, 3.8, clean_pdf_text(d), 0, 1)

    pdf_bytes = pdf.output(dest='S').encode('latin1')
    return Response(content=pdf_bytes, media_type="application/pdf")
